name: CI  # 工作流名称，可以自定义

on:  # 触发条件，定义何时运行工作流
  pull_request:  # 每次创建拉取请求时触发
    branches:
      - main  # 仅在对 main 分支提出 PR 时触发

jobs:  # 定义工作任务
  test:  # 任务名称，可以自定义
    runs-on: ubuntu-latest  # 指定运行的环境为 Ubuntu 最新版本

    steps:
      - name: Checkout code  # 第一步：签出代码
        uses: actions/checkout@v3  # 使用最新的 v3 版本的 actions/checkout

      - name: Set up Python  # 第二步：设置 Python 环境
        uses: actions/setup-python@v4  # 使用最新的 v4 版本的 actions/setup-python
        with:
          python-version: '3.8'  # 指定要使用的 Python 版本

      - name: Install dependencies  # 第三步：安装依赖
        run: |
          python -m pip install --upgrade pip  # 升级 pip
          pip install pytest  # 安装 pytest

      - name: Run tests  # 第四步：运行测试
        run: pytest  # 使用 pytest 运行测试
